# Generated by Django 4.2.2 on 2023-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_taille'),
        ('profiles', '0004_userprofile_followers_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='articles.article'),
        ),
    ]
