# Generated by Django 4.2.2 on 2023-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_taille'),
        ('profiles', '0005_userprofile_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='Auteur', to='articles.article'),
        ),
    ]
