# Generated by Django 4.2.1 on 2023-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userrating_rated_user_alter_userrating_rater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rated_user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='total_ratings',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
