# Generated by Django 4.2.1 on 2023-06-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0011_remove_userrating_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_score',
        ),
        migrations.AddField(
            model_name='userrating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
