# Generated by Django 4.2.1 on 2023-06-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_userprofile_ratings_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='average_rating',
            new_name='average_ratings',
        ),
    ]
