# Generated by Django 4.2.2 on 2023-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_average_rating_userrating_average_ratings'),
    ]

    operations = [
    ]
