# Generated by Django 4.2.2 on 2023-06-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20230618_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='img/profile/boy-1822614.jpg', upload_to='img/profile/'),
        ),
    ]
