# Generated by Django 4.2.2 on 2023-06-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='photo_de_profile',
        ),
    ]
