# Generated by Django 4.2.2 on 2023-06-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('Hommes', 'Hommes'), ('Femmes', 'Femmes'), ('Enfants', 'Enfants')], max_length=20)),
                ('disponibilite', models.CharField(choices=[('Disponible', 'Disponible'), ('NonDisponible', 'NonDisponible')], max_length=20)),
                ('photo', models.ImageField(upload_to='article_photos/%y/%m/%d')),
                ('condition', models.CharField(max_length=100)),
                ('auteur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
