# Generated by Django 4.2.2 on 2023-06-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_created_at_favoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='Date_cr',
        ),
    ]
