# Generated by Django 4.2.1 on 2023-06-11 12:44

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to=articles.models.generate_upload_path),
        ),
    ]
