# Generated by Django 4.2.2 on 2023-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_date_cr_alter_article_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disponibilite',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('NonDisponible', 'NonDisponible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='article_photos/%y/%m/%d'),
        ),
    ]
