# Generated by Django 4.2.2 on 2023-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_disponibilite_alter_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Kids', 'Kids'), ('Sport', 'Sport')], max_length=20),
        ),
    ]
