# Generated by Django 4.2.2 on 2023-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_tel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_de_profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
