# Generated by Django 4.2.2 on 2023-06-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_article_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='article_de',
        ),
    ]
