# Generated by Django 4.2.2 on 2023-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('authentication', '0003_remove_user_article_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
