# Generated by Django 4.2.1 on 2023-06-10 15:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
