# Generated by Django 4.2.2 on 2023-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_photo_de_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_tel',
            field=models.IntegerField(max_length=13, null=True),
        ),
    ]
